### ISSUE TITLE
Undefined bsVersion

### ISSUE THREAD

**Issue by midzer** [fleck/bootstrap.native-loader#1]
Hi,
I'm using just released latest bootstrap.native v2.0.22 for V4 and receive `Cannot read property 'bsVersion' of undefined` error message when using this loader following README instructions.

Trying to specify
```
options: {
    bsVersion: '4'
}
```
in webpack loader options was no help either.

When I remove
```
if (this.options.bsVersion === 3) {
    bsn = bsn3
}
```
in this library from `index.js` everything is working fine though.

Can you give me a hint whats the issue on this case?

Cheers
midzer

**Comment by fleck** [comment]
Just pushed a fix here and to NPM. Just upgrade this plugin and you should be good to go.

**Comment by Kritten** [comment]
Yes thank you, It's working now!

**Comment by fleck** [comment]
@midzer sorry I missed your bug.
