### ISSUE TITLE
Loader always including Bootstrap 3

### ISSUE THREAD

**Issue by jacobwalkr** [fleck/bootstrap.native-loader#2]
I'm using Webpacker in a Rails project and have added `bootstrap.native` and `bootstrap.native-loader` to my project as instructed. The compiled pack always contains the Bootstrap 3 code and not the intended Bootstrap 4.

Here is my `/config/webpack/environment.js`:

```
const { environment } = require('@rails/webpacker')

module.rules = [
    {
        test: /bootstrap\.native/,
        use: {
            loader: 'bootstrap.native-loader',
            options: {
                bsVersion: 4
            }
        }
    }
]

module.exports = environment
```

Adding the options map did nothing but I thought it was worth a try.

In `/app/javascript/packs/application.js`:

```
// Bootstrap Native (removes dependency on jQuery)
import 'bootstrap.native';
```

And, in case it helps, `package.json`:

```
{
  "name": "project",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "3.4",
    "bootstrap.native": "^2.0.22"
  },
  "devDependencies": {
    "bootstrap.native-loader": "^1.0.7",
    "webpack-dev-server": "2.11.2"
  }
}
```

Any idea why I'm ending up with the Bootstrap 3 version of bootstrap.native?

**Comment by jacobwalkr** [comment]
I've worked around this for now by using `require('bootstrap.native/dist/bootstrap-native-v4.js');` in `/app/javascript/packs/application.js` and skipping the loader entirely. I'm still interested in fixing it properly :)

**Comment by fleck** [comment]
Sorry for the late reply. With Rails/webpacker the code to get bootstrap 4 would be:
```javascript
const { environment } = require('@rails/webpacker')

environment.loaders.append('bootstrap.native', {
  test: /bootstrap\.native/,
  use: {
    loader: 'bootstrap.native-loader',
    options: {
      bsVersion: 4
    }
  }
})

module.exports = environment
```
