### ISSUE TITLE
BSN 3.0 released, please update :)

### ISSUE THREAD

**Issue by thednp** [fleck/bootstrap.native-loader#23]
The latest from npm, git and soon CDN is now BSN 3.0.

Please update your loader utility.

Thanks

**Comment by fleck** [comment]
@thednp I don't think this loader is needed with BSN version 3. Now that it ships with ES modules bundlers can tree shake out any unused modules. Also, BSN could even add https://github.com/Andarist/babel-plugin-annotate-pure-calls#babel-plugin-annotate-pure-calls to support tree shaking of individual functions! 

I'm personally migrating away from Bootstrap to React Components / Tailwind CSS, so I don't have the time to invest in updating this loader. Can you remove the recommendation of this loader from the BSN readme and sometime this week I'll write up a deprecation notice in my readme. Thanks for all the work you've put into BSN, it's been great to work with over the years!

**Comment by thednp** [comment]
The official BSN is now BS 4.0 only. 

OK done.
