### ISSUE TITLE
Issue with minify flag

### ISSUE THREAD

**Issue by jdsans** [fleck/bootstrap.native-loader#3]
Hi,

First of all thanks for providing with the loader vanilla bootstrap. Its a great asset and awesome work. So i was trying to minify the custom modules and seems like using the minify flag outputs `undefined` in the compiled webpack file but eliminating the flag seems to be working fine.

```
          {
                test: /bootstrap\.native/,
                use: {
                    loader: 'bootstrap.native-loader',
                    options: {
                        minify : true,
                        only: [
                            'modal',
                            'carousel',
                            'collapse'
                        ]
                    }
                }
            }
```

package.json

```
"bootstrap": "^4.1.0",
"bootstrap.native": "^2.0.22",
"bootstrap.native-loader": "^1.0.7",
```

usage

```
import "bootstrap.native";
```

Thanks

**Comment by fleck** [comment]
Sorry minificiation isn't supported by this loader. That's better handled by other webpack plugins later in the process. https://webpack.js.org/guides/production/#minification
