### ISSUE TITLE
Webpack 4 problems

### ISSUE THREAD

**Issue by TwanoO67** [fleck/bootstrap.native-loader#5]
Hello,

I'm trying to import 'bootstrap.native' in a vue-cli project.
This one is using Webpack 4 and it seems that it's not compatible with your loader.

When adding this to my webpack config:
`config.module.rule('bootstrap.native')
       .use('bootstrap.native')
       .loader('bootstrap.native-loader')
       .options({
         ignore: ['carousel']
       });`

First I have this on compilation:
`Building Native JavaScript for Bootstrap 4 v2.0.24 ..
Unminified Build
Included modules:
    Alert
  Button
  Collapse
  Dropdown
  Modal
  Popover
  ScrollSpy
  Tab
  Tooltip
`

but then, I got the error: 
` Error: Child compilation failed:
  Module build failed (from ./node_modules/html-webpack-plugin/lib/loader.js):
  TypeError: this.cacheable is not a function
`

I tried with version 2.0.23 and 2.0.24 of bootstrap.native without any changes.

My guess is, it's a problem with the html plugin of webpack.
Some other package found solution about that, like you can see here:
https://github.com/kisenka/svg-sprite-loader/commit/20f59ca

I don't know how webpack modules work, but I hope those information can help you :)

Regards,
Antoine

**Comment by fleck** [comment]
Hello, sorry for taking so long to reply. I can confirm that this loader works with webpack 4. It looks like some sort of error with your config. It appears you're missing the test option `test: /bootstrap\.native/` . If you can setup a test repo that I can clone I'd be happy to try and help you out with your problem 😀
