### ISSUE TITLE
Cannot find module 'bootstrap.native/build-module.js'

### ISSUE THREAD

**Issue by luckylooke** [fleck/bootstrap.native-loader#9]
First of all, I dont understand what problem this loader is solving 😊 
But anyway, trying it in my stack I am getting error
```
Module build failed (from ./node_modules/bootstrap.native-loader/index.js):
Error: Cannot find module 'bootstrap.native/build-module.js'
...
```
Which is true.. because current path is 
`bootstrap.native/lib/build-module.js`

Anyway after fixing this, it fails on second require:
```
Error: Cannot find module 'bootstrap.native/build-module-v4.js'
```
So I have rewrite few other lines :D

```
let bsn = require('bootstrap.native/lib/build-module.js')
const { getOptions } = require('loader-utils')

module.exports = function () {
  this.cacheable = true
  const callback = this.async()
  const options = getOptions(this) || {}
  options.bs_version = options.bs_version || 4;

  bsn(options).then((source) => {
    callback(null, source)
  }).catch((error) => {
    callback(error)
  })
}
```

Now it seems to be working :)

**Comment by fleck** [comment]
Just published 2.0.0 to NPM!

**Comment by thednp** [comment]
@luckylooke thanks for testing the new build :)

**Comment by luckylooke** [comment]
I have just tested, works well, thank you 🙂👍

**Comment by luckylooke** [comment]
And now I understand what problem is solved by loader :D It makes you possible to get custom build of bootstrap native into your bundle. :)

**Comment by BrunoViera** [comment]
Thanks for the fix!
